import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, CheckCircle2, Download, FlaskConical, ShieldAlert, TriangleAlert } from 'lucide-react'
import type { CohortSegment, ResearchWaveIncidentCode, ResearchWaveIncidentSeverity, ResearchWaveKind, ResearchWaveReadiness, ResearchWaveStatus, ResearchWaveStatusResponse, ResearchWaveSummary } from '../../shared/types'
import { api } from '../lib/api'

type Props = { onBack: () => void; notify: (type: 'success' | 'error', message: string) => void }
const emptyReadiness: ResearchWaveReadiness = { protocolReviewed: false, controlledRosterReady: false, deletionContactReady: false, supportRouteRehearsed: false }
const labels: Record<CohortSegment, string> = { web_serial: '日更网文', revision_novel: '完稿修订', ai_assisted: 'AI 辅助', other_target: '其他目标' }
const statusLabels: Record<ResearchWaveStatus, string> = { draft: '草稿', recruiting: '招募中', active: '执行中', paused: '已暂停', review: '复核中', closed: '已关闭', cancelled: '已取消' }

export function ResearchWaveWorkspace({ onBack, notify }: Props) {
  const [status, setStatus] = useState<ResearchWaveStatusResponse | null>(null)
  const [kind, setKind] = useState<ResearchWaveKind>('engineering_rehearsal')
  const [windowStart, setWindowStart] = useState(today)
  const [windowEnd, setWindowEnd] = useState(twoWeeksLater)
  const [target, setTarget] = useState(1)
  const [quotas, setQuotas] = useState<Record<CohortSegment, number>>({ web_serial: 1, revision_novel: 0, ai_assisted: 0, other_target: 0 })
  const [readiness, setReadiness] = useState(emptyReadiness)
  const [incidentCode, setIncidentCode] = useState<ResearchWaveIncidentCode>('support_request')
  const [incidentSeverity, setIncidentSeverity] = useState<ResearchWaveIncidentSeverity>('medium')
  const [busy, setBusy] = useState(false)
  const ready = useMemo(() => Object.values(readiness).every(Boolean), [readiness])
  async function refresh() { setStatus(await api.getResearchWaveStatus()) }
  useEffect(() => { void refresh().catch((error) => notify('error', message(error, '波次执行台加载失败'))) }, [])

  function changeKind(next: ResearchWaveKind) {
    setKind(next); const nextTarget = next === 'external_controlled' ? 5 : 1; setTarget(nextTarget); setQuotas(next === 'external_controlled' ? { web_serial: 2, revision_novel: 1, ai_assisted: 1, other_target: 1 } : { web_serial: 1, revision_novel: 0, ai_assisted: 0, other_target: 0 })
  }
  async function createWave() {
    setBusy(true)
    try { await api.createResearchWave({ kind, windowStart: isoStart(windowStart), windowEnd: isoEnd(windowEnd), targetParticipants: target, quotas, readiness }); await refresh(); setReadiness(emptyReadiness); notify('success', kind === 'engineering_rehearsal' ? '工程演练波次已创建；不计入真实执行' : '真实受控波次草稿已创建；尚未产生真实参与者') }
    catch (error) { notify('error', message(error, '波次创建失败')) } finally { setBusy(false) }
  }
  async function transition(wave: ResearchWaveSummary, next: ResearchWaveStatus) { setBusy(true); try { await api.transitionResearchWave(wave.id, next); await refresh(); notify('success', `波次已进入“${statusLabels[next]}”`) } catch (error) { notify('error', message(error, '波次状态变更失败')) } finally { setBusy(false) } }
  async function report(wave: ResearchWaveSummary) { setBusy(true); try { await api.reportResearchWaveIncident(wave.id, incidentCode, incidentSeverity); await refresh(); notify('success', '有界异常已记录；未写入自由文本') } catch (error) { notify('error', message(error, '异常记录失败')) } finally { setBusy(false) } }
  async function resolve(wave: ResearchWaveSummary, incidentId: string) { setBusy(true); try { await api.resolveResearchWaveIncident(wave.id, incidentId); await refresh(); notify('success', '异常已解决并追加不可变事件') } catch (error) { notify('error', message(error, '异常解决失败')) } finally { setBusy(false) } }
  async function exportKit(wave: ResearchWaveSummary) { setBusy(true); try { const kit = await api.exportResearchWaveKit(wave.id); downloadJson(`笔不怠-${wave.displayCode}.bbd-wave-kit`, kit); notify('success', '无名册波次包已导出；不代表真实招募完成') } catch (error) { notify('error', message(error, '波次包导出失败')) } finally { setBusy(false) } }

  if (!status) return <div className="workspace-loading"><span className="brand-mark">笔</span><p>正在读取 R1-C 波次…</p></div>
  return <main className="wave-workspace"><header className="workspace-topbar cohort-topbar"><div className="workspace-title"><button className="icon-button" onClick={onBack} aria-label="返回种子研究台"><ArrowLeft size={18}/></button><span className="mini-brand">笔</span><div><strong>R1-C 受控两周波次</strong><small>1.6.0 · 负责人执行能力</small></div></div><span className="gate-badge no-go" aria-label="R1-C 决策 NO-GO"><TriangleAlert size={14}/><span>真实执行 </span>NO-GO</span></header>
    <section className="wave-content"><header className="page-header"><div><span className="eyebrow">计划不是证据，演练不是真人</span><h1>先冻结边界，再开放一轮真实使用</h1><p>这里不保存名册或联系方式，也不会发送邀请。真实人数只来自归属外部波次的人工核对研究包。</p></div></header>
      <section className="wave-summary" aria-label="R1-C 外部执行状态"><article><strong>{status.externalExecution.waveCount}</strong><span>真实波次</span></article><article><strong>{status.externalExecution.participantCount}</strong><span>真实参与者</span></article><article><strong>{status.externalExecution.twoWeekQualified}</strong><span>两周达标</span></article><article className="no-go"><strong>NO-GO</strong><span>{status.externalExecution.status === 'not_started' ? '真实执行未开始' : '仍需人工复核'}</span></article></section>
      <div className="wave-layout"><section className="panel-card wave-create"><div className="section-title"><FlaskConical size={20}/><div><h2>新建冻结波次</h2><p>工程演练是默认值；真实波次目标必须为 5–10 人。</p></div></div><div className="wave-form"><label>波次类型<select aria-label="波次类型" value={kind} onChange={(event) => changeKind(event.target.value as ResearchWaveKind)}><option value="engineering_rehearsal">工程演练（不计数）</option><option value="external_controlled">真实受控波次</option></select></label><label>开始日期<input aria-label="波次开始日期" type="date" value={windowStart} onChange={(event) => setWindowStart(event.target.value)}/></label><label>结束日期<input aria-label="波次结束日期" type="date" value={windowEnd} onChange={(event) => setWindowEnd(event.target.value)}/></label><label>目标人数<input aria-label="波次目标人数" type="number" min={kind === 'external_controlled' ? 5 : 1} max={10} value={target} onChange={(event) => setTarget(Number(event.target.value))}/></label></div><div className="wave-quotas">{(Object.keys(labels) as CohortSegment[]).map((segment) => <label key={segment}>{labels[segment]}<input aria-label={`${labels[segment]}配额`} type="number" min="0" max="10" value={quotas[segment]} onChange={(event) => setQuotas((current) => ({ ...current, [segment]: Number(event.target.value) }))}/></label>)}</div><fieldset className="cohort-attestation"><legend>开放招募前准备门</legend><Ready checked={readiness.protocolReviewed} onChange={(value) => setReadiness((current) => ({ ...current, protocolReviewed: value }))}>已审阅冻结协议与研究边界</Ready><Ready checked={readiness.controlledRosterReady} onChange={(value) => setReadiness((current) => ({ ...current, controlledRosterReady: value }))}>产品外访问受控名册已就绪</Ready><Ready checked={readiness.deletionContactReady} onChange={(value) => setReadiness((current) => ({ ...current, deletionContactReady: value }))}>参与者删除联系路径已就绪</Ready><Ready checked={readiness.supportRouteRehearsed} onChange={(value) => setReadiness((current) => ({ ...current, supportRouteRehearsed: value }))}>支持与恢复路径已演练</Ready></fieldset><button className="button primary" disabled={busy || !ready} onClick={() => void createWave()}>创建波次草稿</button></section>
        <section className="panel-card wave-boundary"><ShieldAlert size={24}/><h2>真实执行外部门</h2><p>工具不能招募真人、验证身份、替代同意沟通或等待两周。真实波次必须由负责人在产品外维护名册与安全交付渠道。</p><ul><li>演练波次和夹具永不计数</li><li>外部波次包必须在冻结窗口同意</li><li>严重异常未解决不能关闭</li><li>任何数值都不会自动改变 R1</li></ul></section></div>
      <section className="wave-list">{status.waves.map((wave) => <article className="panel-card" key={wave.id}><header><div><span className={`status-pill ${wave.kind === 'external_controlled' ? 'required' : 'active'}`}>{wave.kind === 'external_controlled' ? '真实受控' : '工程演练'}</span><h2>{wave.displayCode}</h2><p>{wave.windowStart.slice(0,10)} → {wave.windowEnd.slice(0,10)} · 目标 {wave.targetParticipants} 人</p></div><strong>{statusLabels[wave.status]}</strong></header><div className="wave-progress"><span>参与者 <b>{wave.participantCount}/{wave.targetParticipants}</b></span><span>两周 <b>{wave.twoWeekQualified}</b></span><span>核心闭环 <b>{wave.coreLoopQualified}</b></span><span>未解决异常 <b>{wave.openIncidents}</b></span></div><div className="inline-actions"><button className="button ghost" onClick={() => void exportKit(wave)}><Download size={14}/>导出无名册波次包</button>{actions(wave).map((next) => <button key={next} className="button secondary" disabled={busy} onClick={() => void transition(wave, next)}>{statusLabels[next]}</button>)}</div>{!['closed','cancelled'].includes(wave.status) && <div className="wave-incident-form"><select aria-label={`${wave.displayCode}异常码`} value={incidentCode} onChange={(event) => setIncidentCode(event.target.value as ResearchWaveIncidentCode)}><option value="support_request">支持请求</option><option value="onboarding_blocked">上手受阻</option><option value="recovery_failed">恢复失败</option><option value="data_loss">数据丢失</option><option value="privacy_request">隐私请求</option><option value="protocol_deviation">协议偏差</option></select><select aria-label={`${wave.displayCode}异常级别`} value={incidentSeverity} onChange={(event) => setIncidentSeverity(event.target.value as ResearchWaveIncidentSeverity)}><option value="low">低</option><option value="medium">中</option><option value="high">高</option><option value="critical">严重</option></select><button className="button ghost" disabled={busy} onClick={() => void report(wave)}>记录异常</button></div>}{wave.incidents.filter((incident) => !incident.resolvedAt).map((incident) => <div className="wave-incident" key={incident.id}><span>{incident.code} · {incident.severity}</span><button className="button ghost" onClick={() => void resolve(wave, incident.id)}>标记已解决</button></div>)}</article>)}{!status.waves.length && <div className="cohort-empty"><FlaskConical size={28}/><strong>尚无波次</strong><span>从工程演练开始，不会产生真实样本。</span></div>}</section>
    </section></main>
}

function actions(wave: ResearchWaveSummary): ResearchWaveStatus[] { const map: Record<ResearchWaveStatus, ResearchWaveStatus[]> = { draft: ['recruiting','cancelled'], recruiting: ['active','cancelled'], active: ['paused','review','cancelled'], paused: ['active','review','cancelled'], review: ['closed','cancelled'], closed: [], cancelled: [] }; return map[wave.status] }
function Ready({ checked, onChange, children }: { checked: boolean; onChange: (value: boolean) => void; children: React.ReactNode }) { return <label className="check-row"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)}/><span>{children}</span></label> }
function today() { return new Date().toISOString().slice(0,10) }
function twoWeeksLater() { const date = new Date(); date.setUTCDate(date.getUTCDate()+14); return date.toISOString().slice(0,10) }
function isoStart(date: string) { return `${date}T00:00:00.000Z` }
function isoEnd(date: string) { return `${date}T23:59:59.999Z` }
function downloadJson(name: string, value: unknown) { const url = URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})); const anchor=document.createElement('a'); anchor.href=url; anchor.download=name; anchor.click(); window.setTimeout(()=>URL.revokeObjectURL(url),500) }
function message(error: unknown, fallback: string) { return error instanceof Error ? error.message : fallback }
